services:
  - type: web
    name: telegram-iptv-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node telegram_bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        scope: build
        sync: false
      - key: WEBHOOK_URL
        scope: build
        sync: false
      - key: DB_HOST
        scope: build
        sync: false
      - key: DB_USER
        scope: build
        sync: false
      - key: DB_PASS
        scope: build
        sync: false
      - key: DB_NAME
        scope: build
        sync: false
      - key: PANEL_API_URL
        scope: build
        sync: false
      - key: PORT
        value: "3000"
        scope: build
        sync: false
